logging:
  level:
    io.rsocket: info
spring:
  output:
    ansi:
      enabled: always
#  cloud:
#    gateway:
#      rsocket:
#        client:
#          broker:
#            host: gateway1-127-0-0-1.nip.io
#            port: 7001
#            #host: gateway2-127-0-0-1.nip.io
#            #port: 7002
#            ##host: gateway3-127-0-0-1.nip.io
#            ##port: 7003
  cloud:
    gateway:
      rsocket:
        client:
          route-id: 444
          service-name: ping
          tags:
            INSTANCE_NAME: ping-in-1
          broker:
            host: gateway1-127-0-0-1.nip.io
            port: 7001
          #forwarding:
          #  pong-2:
          #    service_name: pong
          #  pong-rc:
          #    service_name: pong
server:
  port: 8001
---
spring:
  profiles: ping2
  cloud:
    gateway:
      rsocket:
        client:
          route-id: 4444
          service-name: ping
          tags:
            INSTANCE_NAME: ping-in-2
          broker:
            host: gateway1-127-0-0-1.nip.io
            port: 7001
server:
  port: 0
