name: CI
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to triggre manual jobs
        required: false
        default: ''
  pull_request:
    branches: [ main, master ]
  push:
env:
  JAVA_VERSION: 11
jobs:
  tests:
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: ci
      with:
        path: |
          ~/.npm
          ~/.node
          ~/.local
          ~/.gradle
          ~/.docker
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - uses: actions/setup-node@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    #- run: cd $GITHUB_WORKSPACE ; ./mvnw clean ; ./mvnw
    - run: |
        source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
        stop_any 7001 7002 7003 7004 8080 8081 8082 8083 8084 8085
    - run: |
        ./mvnw compile spring-boot:start -f gateway -Pgw1
        ./mvnw compile spring-boot:start -f gateway -Pgw2
        ./mvnw compile spring-boot:start -f gateway -Pgw3
    - run: |
        ./mvnw compile spring-boot:start -f pong
        sleep 3s
        ./mvnw compile spring-boot:start -f ping
        sleep 30s
  dependency-updates:
    if: contains(github.event.inputs.trigger, 'M')
      || startsWith(github.event.inputs.trigger, 'm')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - run: |
        echo "Trigger: ${{ github.event.inputs.trigger }}"
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: ci
      with:
        path: |
          ~/.npm
          ~/.node
          ~/.local
          ~/.gradle
          ~/.docker
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-plugin-updates
    - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-property-updates
    - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-parent-updates
